version: 2.1

jobs:
  test:
    docker:
      - image: python:3.8  # Use Python image to run pytest
    working_directory: ~/project  # Set working directory to repo root
    steps:
      - checkout  # Clone the repo
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest
      - run:
          name: Verify project structure
          command: ls -R  # Check if files exist inside CircleCI
      - run:
          name: Run Tests with Pytest
          command: |
            pytest tests/ --junitxml=test-results/junit.xml  # Run pytest on tests folder

      # Store test results
      - store_test_results:
          path: test-results

  deploy:
    docker:
      - image: curlimages/curl:latest
    steps:
      - run:
          name: Debug API Key
          command: echo "RENDER_API_KEY is set"

      - run:
          name: Trigger Render Deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              curl -X POST "https://api.render.com/v1/services/srv-cunipvogph6c73etqqo0/deploys" \
                   -H "Authorization: Bearer ${RENDER_API_KEY}"
            else
              echo "Skipping deployment: Not on main branch."
            fi

workflows:
  test-and-deploy:
    jobs:
      - test  #  Runs on all branches
      - deploy:
          requires:
            - test  #  Only deploy if tests pass
          filters:
            branches:
              only: main  #  Deploys only when pushing to main
