version: 2.1

jobs:
  test:
    docker:
      - image: python:3.8  # Use Python image to run pytest
    steps:
      - checkout  # Clone the repo
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest
      - run:
          name: Run Tests with Pytest
          command: |
            pytest --junitxml=test-results/junit.xml  # Run pytest & save results

      # Store test results
      - store_test_results:
          path: test-results

workflows:
  test-workflow:
    jobs:
      - test
